// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'profile_finder';
  static const String PROJECT_VERSION = '1.0.0+3';
  static const String CEMENT_PROFILES = 'assets/data/cement_profiles.json';
  static const String STEEL_PROFILES = 'assets/data/steel_profiles.json';
  static const String TILE_PROFILES_UK_PHASE2 = 'assets/data/tile_profiles_uk_phase2.json';
}
